In [346]:
import requests
import json
import pandas as pd
import datetime

In [347]:
# Getting the match timeline as a JSON
r = requests.get(url="https://acs.leagueoflegends.com/v1/stats/game/TRLH3/1001970008/timeline?gameHash=7aa4a96045584cfe")
response = json.loads(r.content)

In [348]:
# Creating vars with the info we need (wards)

## Getting the frames
frames = response["frames"]

## Mapping all events into a list
events = list(map(lambda y: y["events"], frames)) 

## Mapping the participant frames into a list
participants = list(map(lambda y: y["participantFrames"], frames)) 

## Grouping al vision related events into a single list
vision_events = list(map(lambda x: list(filter(lambda y: (y["type"] == "WARD_PLACED" or y["type"] == "WARD_KILL"), x)), events))

In [349]:
# Merging both vision events with the info of the participant of the event

## Creating a list that we will poblate later with all the data
result = []

##Iterating through events frames with the index information
for index, events in enumerate(vision_events):
    ### For every event in that event frame do:
    for event in events:
        #### Check whether if is a placement or a kill to get the participant ID to get the participant info
        if event["type"] == "WARD_PLACED": pid = event["creatorId"]
        else: pid = event["killerId"]
        #### Getting the participant info
        participant = participants[index].get(str(pid))
        #### Merging that info
        merged = dict(list(event.items()) + list(participant.items()))
        #### Adding the frame number
        merged["nFrame"] = index
        #### Appending the data as a new item to the list previously created
        result.append(merged)

## Transforming the list into a Pandas DataFrame 
resultdf = pd.DataFrame.from_dict(result)

In [350]:
resultdf['x_pos'] = resultdf['position'].apply(lambda d: d['x'])
resultdf['y_pos'] = resultdf['position'].apply(lambda d: d['y'])

resultdf['timestamp'] = resultdf['timestamp'].apply(lambda d: '{:02d}:{:02d}'.format(int(divmod(d/1000, 60)[0]), int(divmod(d/1000, 60)[1])))
resultdf

,creatorId,currentGold,dominionScore,jungleMinionsKilled,killerId,level,minionsKilled,nFrame,participantId,position,teamScore,timestamp,totalGold,type,wardType,xp,x_pos,y_pos
0,7.0,0,0,0,NaN,1,0,1,7,"{'x': 7263, 'y': 9831}",0,01:05,500,WARD_PLACED,YELLOW_TRINKET,0,7263,9831
1,6.0,0,0,0,NaN,1,0,1,6,"{'x': 4510, 'y': 11722}",0,01:12,500,WARD_PLACED,YELLOW_TRINKET,0,4510,11722
2,4.0,32,0,0,NaN,1,1,2,4,"{'x': 12240, 'y': 1695}",0,02:05,532,WARD_PLACED,YELLOW_TRINKET,38,12240,1695
3,10.0,30,0,0,NaN,1,1,2,10,"{'x': 12549, 'y': 2695}",0,02:19,530,WARD_PLACED,YELLOW_TRINKET,134,12549,2695
4,2.0,114,0,6,NaN,2,0,2,2,"{'x': 7267, 'y': 3888}",0,02:43,614,WARD_PLACED,YELLOW_TRINKET,346,7267,3888
5,9.0,274,0,0,NaN,2,8,3,9,"{'x': 12446, 'y': 2910}",0,03:08,774,WARD_PLACED,YELLOW_TRINKET,326,12446,2910
6,4.0,395,0,0,NaN,2,14,3,4,"{'x': 11558, 'y': 1778}",0,03:16,895,WARD_PLACED,YELLOW_TRINKET,422,11558,1778
7,NaN,163,0,0,10.0,2,1,3,10,"{'x': 11946, 'y': 2818}",0,03:19,663,WARD_KILL,YELLOW_TRINKET,326,11946,2818
8,5.0,233,0,0,NaN,2,3,3,5,"{'x': 12847, 'y': 2100}",0,03:23,733,WARD_PLACED,YELLOW_TRINKET,422,12847,2100
9,NaN,163,0,0,10.0,2,1,3,10,"{'x': 11946, 'y': 2818}",0,03:26,663,WARD_KILL,YELLOW_TRINKET,326,11946,2818
10,6.0,308,0,0,NaN,2,10,3,6,"{'x': 3157, 'y': 13611}",0,03:44,808,WARD_PLACED,YELLOW_TRINKET,588,3157,13611
11,2.0,405,0,8,NaN,2,0,3,2,"{'x': 8465, 'y': 2156}",0,03:54,905,WARD_PLACED,YELLOW_TRINKET,655,8465,2156
12,7.0,435,0,8,NaN,3,0,3,7,"{'x': 12417, 'y': 6649}",0,03:56,935,WARD_PLACED,YELLOW_TRINKET,726,12417,6649
13,3.0,413,0,0,NaN,3,14,3,3,"{'x': 6898, 'y': 6494}",0,03:57,913,WARD_PLACED,YELLOW_TRINKET,798,6898,6494
14,NaN,824,0,13,7.0,4,1,4,7,"{'x': 3426, 'y': 8917}",0,04:00,1324,WARD_KILL,YELLOW_TRINKET,1201,3426,8917
15,3.0,736,0,0,NaN,4,25,4,3,"{'x': 6581, 'y': 8402}",0,04:00,1236,WARD_PLACED,YELLOW_TRINKET,1416,6581,8402
16,5.0,406,0,0,NaN,3,4,4,5,"{'x': 12799, 'y': 2223}",0,04:18,906,WARD_PLACED,YELLOW_TRINKET,751,12799,2223
17,1.0,31,0,0,NaN,3,18,4,1,"{'x': 394, 'y': 461}",0,04:21,1111,WARD_PLACED,YELLOW_TRINKET,1092,394,461
18,9.0,685,0,0,NaN,3,22,4,9,"{'x': 13051, 'y': 3296}",0,04:30,1185,WARD_PLACED,YELLOW_TRINKET,914,13051,3296
19,8.0,278,0,0,NaN,5,37,5,8,"{'x': 8125, 'y': 6433}",0,05:02,1603,WARD_PLACED,UNDEFINED,1862,8125,6433
20,8.0,278,0,0,NaN,5,37,5,8,"{'x': 8125, 'y': 6433}",0,05:05,1603,WARD_PLACED,YELLOW_TRINKET,1862,8125,6433
21,10.0,573,0,0,NaN,4,7,5,10,"{'x': 13218, 'y': 2603}",0,05:16,1073,WARD_PLACED,YELLOW_TRINKET,1224,13218,2603
22,7.0,30,0,23,NaN,4,1,5,7,"{'x': 12410, 'y': 12313}",0,05:29,1605,WARD_PLACED,UNDEFINED,1430,12410,12313
23,2.0,20,0,23,NaN,4,0,5,2,"{'x': 2099, 'y': 1085}",0,05:34,1595,WARD_PLACED,SIGHT_WARD,1612,2099,1085
24,4.0,1510,0,0,NaN,4,50,6,4,"{'x': 12901, 'y': 2467}",0,06:05,2010,WARD_PLACED,YELLOW_TRINKET,1580,12901,2467
25,7.0,303,0,29,NaN,5,3,6,7,"{'x': 8382, 'y': 6237}",0,06:11,1878,WARD_PLACED,YELLOW_TRINKET,1810,8382,6237
26,5.0,775,0,0,NaN,4,7,6,5,"{'x': 13524, 'y': 2731}",0,06:26,1275,WARD_PLACED,YELLOW_TRINKET,1521,13524,2731
27,3.0,1397,0,0,NaN,6,46,6,3,"{'x': 5444, 'y': 6136}",0,06:49,1897,WARD_PLACED,YELLOW_TRINKET,2498,5444,6136
28,NaN,1397,0,0,3.0,6,46,6,3,"{'x': 5444, 'y': 6136}",0,06:56,1897,WARD_KILL,UNDEFINED,2498,5444,6136
29,3.0,1397,0,0,NaN,6,46,6,3,"{'x': 5444, 'y': 6136}",0,06:57,1897,WARD_PLACED,UNDEFINED,2498,5444,6136
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,7.0,445,0,163,NaN,16,35,36,7,"{'x': 6967, 'y': 13202}",0,36:45,11610,WARD_PLACED,UNDEFINED,14727,6967,13202
352,5.0,476,0,0,NaN,14,69,36,5,"{'x': 7083, 'y': 6703}",0,36:51,9552,WARD_PLACED,SIGHT_WARD,12163,7083,6703
353,1.0,800,0,16,NaN,18,323,36,1,"{'x': 13248, 'y': 3645}",0,36:53,15164,WARD_PLACED,BLUE_TRINKET,19598,13248,3645
354,NaN,800,0,16,1.0,18,323,36,1,"{'x': 13248, 'y': 3645}",0,36:56,15164,WARD_KILL,BLUE_TRINKET,19598,13248,3645
355,5.0,476,0,0,NaN,14,69,36,5,"{'x': 7083, 'y': 6703}",0,36:57,9552,WARD_PLACED,UNDEFINED,12163,7083,6703
356,4.0,429,0,8,NaN,16,329,37,4,"{'x': 9571, 'y': 9227}",0,37:04,14184,WARD_PLACED,UNDEFINED,16210,9571,9227
357,NaN,326,0,174,2.0,17,62,37,2,"{'x': 5082, 'y': 9178}",0,37:11,14506,WARD_KILL,UNDEFINED,18159,5082,9178
358,4.0,429,0,8,NaN,16,329,37,4,"{'x': 9571, 'y': 9227}",0,37:14,14184,WARD_PLACED,UNDEFINED,16210,9571,9227
359,5.0,716,0,0,NaN,14,70,37,5,"{'x': 9948, 'y': 9363}",0,37:22,9791,WARD_PLACED,SIGHT_WARD,12385,9948,9363
360,6.0,392,0,3,NaN,17,336,37,6,"{'x': 14340, 'y': 14391}",0,37:47,13042,WARD_PLACED,BLUE_TRINKET,17490,14340,14391
361,6.0,392,0,3,NaN,17,336,37,6,"{'x': 14340, 'y': 14391}",0,37:52,13042,WARD_PLACED,UNDEFINED,17490,14340,14391
362,3.0,299,0,17,NaN,18,360,37,3,"{'x': 9824, 'y': 9362}",0,37:56,16518,WARD_PLACED,BLUE_TRINKET,20825,9824,9362
363,NaN,964,0,8,4.0,17,333,38,4,"{'x': 13588, 'y': 10268}",0,38:06,14718,WARD_KILL,UNDEFINED,16723,13588,10268
364,4.0,964,0,8,NaN,17,333,38,4,"{'x': 13588, 'y': 10268}",0,38:13,14718,WARD_PLACED,UNDEFINED,16723,13588,10268
365,4.0,964,0,8,NaN,17,333,38,4,"{'x': 13588, 'y': 10268}",0,38:21,14718,WARD_PLACED,UNDEFINED,16723,13588,10268
366,9.0,842,0,4,NaN,17,352,38,9,"{'x': 12795, 'y': 12228}",0,38:26,13211,WARD_PLACED,BLUE_TRINKET,16494,12795,12228
367,4.0,964,0,8,NaN,17,333,38,4,"{'x': 13588, 'y': 10268}",0,38:27,14718,WARD_PLACED,UNDEFINED,16723,13588,10268
368,NaN,995,0,175,2.0,18,71,38,2,"{'x': 11646, 'y': 11235}",0,38:27,15174,WARD_KILL,BLUE_TRINKET,19035,11646,11235
369,NaN,1200,0,0,5.0,15,70,38,5,"{'x': 12999, 'y': 9768}",0,38:31,10275,WARD_KILL,UNDEFINED,13276,12999,9768
370,NaN,683,0,0,10.0,14,30,38,10,"{'x': 13303, 'y': 9948}",0,38:41,8318,WARD_KILL,UNDEFINED,11768,13303,9948
371,5.0,1200,0,0,NaN,15,70,38,5,"{'x': 12999, 'y': 9768}",0,38:41,10275,WARD_PLACED,UNDEFINED,13276,12999,9768
372,NaN,1021,0,166,7.0,16,45,38,7,"{'x': 10068, 'y': 13615}",0,38:43,12186,WARD_KILL,UNDEFINED,15417,10068,13615
373,4.0,964,0,8,NaN,17,333,38,4,"{'x': 13588, 'y': 10268}",0,38:49,14718,WARD_PLACED,BLUE_TRINKET,16723,13588,10268
374,NaN,683,0,0,10.0,14,30,38,10,"{'x': 13303, 'y': 9948}",0,38:51,8318,WARD_KILL,BLUE_TRINKET,11768,13303,9948
375,4.0,964,0,8,NaN,17,333,38,4,"{'x': 13588, 'y': 10268}",0,38:54,14718,WARD_PLACED,UNDEFINED,16723,13588,10268
376,7.0,1698,0,166,NaN,16,53,39,7,"{'x': 5798, 'y': 10437}",0,39:06,12864,WARD_PLACED,UNDEFINED,16288,5798,10437
377,10.0,1034,0,0,NaN,14,33,39,10,"{'x': 7122, 'y': 11532}",0,39:08,8669,WARD_PLACED,SIGHT_WARD,12047,7122,11532
378,NaN,2914,0,26,1.0,18,358,39,1,"{'x': 6592, 'y': 11332}",0,39:13,17778,WARD_KILL,BLUE_TRINKET,22994,6592,11332
379,1.0,2914,0,26,NaN,18,358,39,1,"{'x': 6592, 'y': 11332}",0,39:42,17778,WARD_PLACED,BLUE_TRINKET,22994,6592,11332
380,NaN,1698,0,166,7.0,16,53,39,7,"{'x': 5798, 'y': 10437}",0,39:44,12864,WARD_KILL,BLUE_TRINKET,16288,5798,10437

In [ ]:
# Some corrections over the data

## Removing the participantID column since the data is redundant because we already have the ID in the creatorId or in the killerId
del resultdf["participantId"]
## Removing as well the position since we previously added two new columns with that data
del resultdf["position"]

In [266]:
# In order to convert the ids into integers we need to replace NA values with something acceptable that clearly indicates that the value represents something completly different as expectet, like -1
resultdf = resultdf.fillna(-1)

,creatorId,currentGold,dominionScore,jungleMinionsKilled,killerId,level,minionsKilled,nFrame,teamScore,timestamp,totalGold,type,wardType,xp,x_pos,y_pos
0,7,0,0,0,NA,1,0,1,0,65502,500,WARD_PLACED,YELLOW_TRINKET,0,7263,9831
1,6,0,0,0,NA,1,0,1,0,72603,500,WARD_PLACED,YELLOW_TRINKET,0,4510,11722
2,4,32,0,0,NA,1,1,2,0,125952,532,WARD_PLACED,YELLOW_TRINKET,38,12240,1695
3,10,30,0,0,NA,1,1,2,0,139444,530,WARD_PLACED,YELLOW_TRINKET,134,12549,2695
4,2,114,0,6,NA,2,0,2,0,163238,614,WARD_PLACED,YELLOW_TRINKET,346,7267,3888
5,9,274,0,0,NA,2,8,3,0,188097,774,WARD_PLACED,YELLOW_TRINKET,326,12446,2910
6,4,395,0,0,NA,2,14,3,0,196908,895,WARD_PLACED,YELLOW_TRINKET,422,11558,1778
7,NA,163,0,0,10,2,1,3,0,199501,663,WARD_KILL,YELLOW_TRINKET,326,11946,2818
8,5,233,0,0,NA,2,3,3,0,203391,733,WARD_PLACED,YELLOW_TRINKET,422,12847,2100
9,NA,163,0,0,10,2,1,3,0,206182,663,WARD_KILL,YELLOW_TRINKET,326,11946,2818
10,6,308,0,0,NA,2,10,3,0,224107,808,WARD_PLACED,YELLOW_TRINKET,588,3157,13611
11,2,405,0,8,NA,2,0,3,0,234718,905,WARD_PLACED,YELLOW_TRINKET,655,8465,2156
12,7,435,0,8,NA,3,0,3,0,236571,935,WARD_PLACED,YELLOW_TRINKET,726,12417,6649
13,3,413,0,0,NA,3,14,3,0,237835,913,WARD_PLACED,YELLOW_TRINKET,798,6898,6494
14,NA,824,0,13,7,4,1,4,0,240190,1324,WARD_KILL,YELLOW_TRINKET,1201,3426,8917
15,3,736,0,0,NA,4,25,4,0,240320,1236,WARD_PLACED,YELLOW_TRINKET,1416,6581,8402
16,5,406,0,0,NA,3,4,4,0,258526,906,WARD_PLACED,YELLOW_TRINKET,751,12799,2223
17,1,31,0,0,NA,3,18,4,0,261906,1111,WARD_PLACED,YELLOW_TRINKET,1092,394,461
18,9,685,0,0,NA,3,22,4,0,270989,1185,WARD_PLACED,YELLOW_TRINKET,914,13051,3296
19,8,278,0,0,NA,5,37,5,0,302356,1603,WARD_PLACED,UNDEFINED,1862,8125,6433
20,8,278,0,0,NA,5,37,5,0,305114,1603,WARD_PLACED,YELLOW_TRINKET,1862,8125,6433
21,10,573,0,0,NA,4,7,5,0,316167,1073,WARD_PLACED,YELLOW_TRINKET,1224,13218,2603
22,7,30,0,23,NA,4,1,5,0,329736,1605,WARD_PLACED,UNDEFINED,1430,12410,12313
23,2,20,0,23,NA,4,0,5,0,334959,1595,WARD_PLACED,SIGHT_WARD,1612,2099,1085
24,4,1510,0,0,NA,4,50,6,0,365371,2010,WARD_PLACED,YELLOW_TRINKET,1580,12901,2467
25,7,303,0,29,NA,5,3,6,0,371687,1878,WARD_PLACED,YELLOW_TRINKET,1810,8382,6237
26,5,775,0,0,NA,4,7,6,0,386708,1275,WARD_PLACED,YELLOW_TRINKET,1521,13524,2731
27,3,1397,0,0,NA,6,46,6,0,409940,1897,WARD_PLACED,YELLOW_TRINKET,2498,5444,6136
28,NA,1397,0,0,3,6,46,6,0,416509,1897,WARD_KILL,UNDEFINED,2498,5444,6136
29,3,1397,0,0,NA,6,46,6,0,417677,1897,WARD_PLACED,UNDEFINED,2498,5444,6136
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,7,445,0,163,NA,16,35,36,0,2205895,11610,WARD_PLACED,UNDEFINED,14727,6967,13202
352,5,476,0,0,NA,14,69,36,0,2211460,9552,WARD_PLACED,SIGHT_WARD,12163,7083,6703
353,1,800,0,16,NA,18,323,36,0,2213646,15164,WARD_PLACED,BLUE_TRINKET,19598,13248,3645
354,NA,800,0,16,1,18,323,36,0,2216301,15164,WARD_KILL,BLUE_TRINKET,19598,13248,3645
355,5,476,0,0,NA,14,69,36,0,2217907,9552,WARD_PLACED,UNDEFINED,12163,7083,6703
356,4,429,0,8,NA,16,329,37,0,2224379,14184,WARD_PLACED,UNDEFINED,16210,9571,9227
357,NA,326,0,174,2,17,62,37,0,2231603,14506,WARD_KILL,UNDEFINED,18159,5082,9178
358,4,429,0,8,NA,16,329,37,0,2234508,14184,WARD_PLACED,UNDEFINED,16210,9571,9227
359,5,716,0,0,NA,14,70,37,0,2242055,9791,WARD_PLACED,SIGHT_WARD,12385,9948,9363
360,6,392,0,3,NA,17,336,37,0,2267396,13042,WARD_PLACED,BLUE_TRINKET,17490,14340,14391
361,6,392,0,3,NA,17,336,37,0,2272665,13042,WARD_PLACED,UNDEFINED,17490,14340,14391
362,3,299,0,17,NA,18,360,37,0,2276547,16518,WARD_PLACED,BLUE_TRINKET,20825,9824,9362
363,NA,964,0,8,4,17,333,38,0,2286745,14718,WARD_KILL,UNDEFINED,16723,13588,10268
364,4,964,0,8,NA,17,333,38,0,2293990,14718,WARD_PLACED,UNDEFINED,16723,13588,10268
365,4,964,0,8,NA,17,333,38,0,2301222,14718,WARD_PLACED,UNDEFINED,16723,13588,10268
366,9,842,0,4,NA,17,352,38,0,2306448,13211,WARD_PLACED,BLUE_TRINKET,16494,12795,12228
367,4,964,0,8,NA,17,333,38,0,2307301,14718,WARD_PLACED,UNDEFINED,16723,13588,10268
368,NA,995,0,175,2,18,71,38,0,2307797,15174,WARD_KILL,BLUE_TRINKET,19035,11646,11235
369,NA,1200,0,0,5,15,70,38,0,2311134,10275,WARD_KILL,UNDEFINED,13276,12999,9768
370,NA,683,0,0,10,14,30,38,0,2321458,8318,WARD_KILL,UNDEFINED,11768,13303,9948
371,5,1200,0,0,NA,15,70,38,0,2321556,10275,WARD_PLACED,UNDEFINED,13276,12999,9768
372,NA,1021,0,166,7,16,45,38,0,2323876,12186,WARD_KILL,UNDEFINED,15417,10068,13615
373,4,964,0,8,NA,17,333,38,0,2329425,14718,WARD_PLACED,BLUE_TRINKET,16723,13588,10268
374,NA,683,0,0,10,14,30,38,0,2331063,8318,WARD_KILL,BLUE_TRINKET,11768,13303,9948
375,4,964,0,8,NA,17,333,38,0,2334725,14718,WARD_PLACED,UNDEFINED,16723,13588,10268
376,7,1698,0,166,NA,16,53,39,0,2346240,12864,WARD_PLACED,UNDEFINED,16288,5798,10437
377,10,1034,0,0,NA,14,33,39,0,2348556,8669,WARD_PLACED,SIGHT_WARD,12047,7122,11532
378,NA,2914,0,26,1,18,358,39,0,2353165,17778,WARD_KILL,BLUE_TRINKET,22994,6592,11332
379,1,2914,0,26,NA,18,358,39,0,2382500,17778,WARD_PLACED,BLUE_TRINKET,22994,6592,11332
380,NA,1698,0,166,7,16,53,39,0,2384522,12864,WARD_KILL,BLUE_TRINKET,16288,5798,10437

In [265]:
# Then we convert the float values of the id columns into integer values
resultdf["creatorId"] = resultdf["creatorId"].astype(int)
resultdf["killerId"] = resultdf["killerId"].astype(int)
# Then we replace the -1 for NA 
resultdf = resultdf.replace(to_replace=-1, value="NA")
# And finally we export the dataframe into a CSV
resultdf.to_csv("vision_events.csv")